//
//  Literal.swift
//  FAVE
//
//  Created by Nazih Shoura on 04/08/2016.
//  Copyright © 2016 kfit. All rights reserved.
//

import Foundation

let literal = Literal()

struct Literal {
    let SettingsProviderDefault = "SettingsProviderDefault"
    let ListingOutletView = "ListingOutletView"
    let ChangeStagingViewController = "ChangeStagingViewController"
    let StagingContentTableViewCell = "StagingContentTableViewCell"
    let ChangeStagingSubmitTableViewCell = "ChangeStagingSubmitTableViewCell"
    let HomeCarouselSection = "HomeCarouselSection"
    let LocationServiceDefault = "LocationServiceDefault"
    let ListingHeaderPhotoTableViewCell = "ListingHeaderPhotoTableViewCell"
    let ActivePromoCountView = "ActivePromoCountView"
    let ClassSession = "ClassSession"
    let ListingGeneralSectionHeader = "ListingGeneralSectionHeader"
    let ListingDetailsTableViewCell = "ListingDetailsTableViewCell"
    let ListingBookTableViewCell = "ListingBookTableViewCell"
    let ListingAboutTableViewCell = "ListingAboutTableViewCell"
    let ListingBuyNowTableViewCell = "ListingBuyNowTableViewCell"
    let ListingNextSessionTableViewCell = "ListingNextSessionTableViewCell"
    let ListingReviewTableViewCell = "ListingReviewTableViewCell"
    let ListingDateTimeSlotTableViewCell = "ListingDateTimeSlotTableViewCell"
    let ListingOutletTableViewCell = "ListingOutletTableViewCell"
    let ListingMultipleOutletsTableViewCell = "ListingMultipleOutletsTableViewCell"
    let ListingStandardInfoTableViewCell = "ListingStandardInfoTableViewCell"
    let ListingInfoAmenityTableViewCell = "ListingInfoAmenityTableViewCell"
    let ListingGalleryTableViewCell = "ListingGalleryTableViewCell"
    let ListingThingsToKnowTableViewCell = "ListingThingsToKnowTableViewCell"
    let ListingWhatYouGetTableViewCell = "ListingWhatYouGetTableViewCell"
    let RedemptionThingsToKnowTableViewCell = "RedemptionThingsToKnowTableViewCell"
    let ListingOutletLocationTableViewCell = "ListingOutletLocationTableViewCell"
    let ListingCancellationTableViewCell = "ListingCancellationTableViewCell"
    let ListingCollectionTableViewCell = "ListingCollectionTableViewCell"
    let ListingPromoCodeTableViewCell = "ListingPromoCodeTableViewCell"
    let MultipleOutletsViewController = "MultipleOutletsViewController"
    let ListingViewController = "ListingViewController"
    let CitiesHeaderView = "CitiesHeaderView"
    let Company = "Company"
    let Category = "Category"
    let CitiesTableViewCell = "CitiesTableViewCell"
    let ListingGeneralSectionFooter = "ListingGeneralSectionFooter"
    let CityProviderDefault = "CityProviderDefault"
    let ConfirmationTimeTableViewCell = "ConfirmationTimeTableViewCell"
    let ConfirmationDetailsTableViewCell = "ConfirmationDetailsTableViewCell"
    let ActivityHeaderView = "ActivityHeaderView"
    let AboutUsViewController = "AboutUsViewController"
    let CitiesViewController = "CitiesViewController"
    let Listing = "Listing"
    let ConfirmationQuantityTableViewCell = "ConfirmationQuantityTableViewCell"
    let ConfirmationTitleTableViewCell = "ConfirmationTitleTableViewCell"
    let ConfirmationPriceTableViewCell = "ConfirmationPriceTableViewCell"
    let ConfirmationViewController = "ConfirmationViewController"
    let ListingsLocationNavigationTitleModel = "ListingsLocationNavigationTitleModel"
    let Cookie = "com.kfit.fave.cookie"
    let ReviewViewController = "ReviewViewController"
    let WriteReviewViewController = "WriteReviewViewController"
    let HomeViewController = "HomeViewController"
    let HomePartnersCarouselTableViewCell = "HomePartnersCarouselTableViewCell"
    let HomeCollectionsCarouselTableViewCell = "HomeCollectionsCarouselTableViewCell"
    let HomeListingCollectionViewCell = "HomeListingCollectionViewCell"
    let HomeOffersCarouselTableViewCell = "HomeOffersCarouselTableViewCell"
    let HomeFiltersTableViewCell = "HomeFiltersTableViewCell"
    let HomeHeaderTableViewCell = "HomeHeaderTableViewCell"
    let HomeListingTableViewCell = "HomeListingTableViewCell"
    let HomeFeaturedOfferTableViewCell = "HomeFeaturedOfferTableViewCell"
    let HomeInviteFriendTableViewCell = "HomeInviteFriendTableViewCell"
    let City = "City"
    let User = "User"
    let ChannelTableViewCell = "ChannelTableViewCell"
    let CreateChannelViewController = "CreateChannelViewController"
    let ChatViewController = "ChatViewController"
    let ChatContainerViewController = "ChatContainerViewController"
    let EmptyChannelsViewController = "EmptyChannelsViewController"
    let ChannelProviderDefault = "ChannelProviderDefault"
    let ContactsViewController = "ContactsViewController"
    let ContactProviderDefault = "ContactProviderDefault"
    let ContactViewTableViewCell = "ContactViewTableViewCell"
    let Contact = "Contact"
    let ContactsBundle = "ContactsBundle"
    let FaveContactHeaderTableViewCell = "FaveContactHeaderTableViewCell"
    let NonFaveContactHeaderTableViewCell = "NonFaveContactHeaderTableViewCell"
    let ChannelInfoHeaderTableViewCell = "ChannelInfoHeaderTableViewCell"
    let ChannelInfoFriendsHeaderTableViewCell = "ChannelInfoFriendsHeaderTableViewCell"
    let ChannelInfoFriendTableViewCell = "ChannelInfoFriendTableViewCell"
    let ChannelInfoLeaveChatTableViewCell = "ChannelInfoLeaveChatTableViewCell"
    let ChannelInfoSeparatorTableViewCell = "ChannelInfoSeparatorTableViewCell"
    let ChanelsContainerViewController = "ChanelsContainerViewController"
    let Channel = "Channel"
    let ChatParticipant = "ChatParticipant"
    let ShareMessage = "ShareMessage"
    let ChannelInvitationsTableViewCell = "ChannelInvitationsTableViewCell"
    let ChannelCreditsTableViewCell     = "ChannelCreditsTableViewCell"
    let ChannelsHeaderViewTableViewCell = "ChannelsHeaderViewTableViewCell"
    let BroadcastMessageCollectionViewCell = "BroadcastMessageCollectionViewCell"
    let ChannelInfoInviteFriendsTableViewCell = "ChannelInfoInviteFriendsTableViewCell"
    let CountriesCodesTableViewCell = "CountriesCodesTableViewCell"
    let CountriesCodesViewController = "CountriesCodesViewController"
    let EnterPhoneNumberViewController = "EnterPhoneNumberViewController"
    let VerifyCodeViewController = "VerifyCodeViewController"
    let NearbyViewController = "NearbyViewController"
    let FilterViewController = "FilterViewController"
    let MyFaveEmptyResultTableViewCell = "MyFaveEmptyResultTableViewCell"
    let FilterPickupTableViewCell = "FilterPickupTableViewCell"
    let FilterCategoriesTableViewCell = "FilterCategoriesTableViewCell"
    let ListingsHeaderTableViewCell = "ListingsHeaderTableViewCell"
    let FilterIsOffTableViewCell = "FilterIsOffTableViewCell"
    let FilterIsOnTableViewCell = "FilterIsOnTableViewCell"
    let FilterSectionSingleCollectionViewCell = "FilterSectionSingleCollectionViewCell"
    let FilterSectionSingleTableViewCell = "FilterSectionSingleTableViewCell"
    let ConfirmationPromoEmptyTableViewCell = "ConfirmationPromoEmptyTableViewCell"
    let ConfirmationFinalPriceTableViewCell = "ConfirmationFinalPriceTableViewCell"
    let ConfirmationPromoTableViewCell = "ConfirmationPromoTableViewCell"
    let HomeFaveInformationTableViewCell = "HomeFaveInformationTableViewCell"
    let ConfirmationCreditTableViewCell = "ConfirmationCreditTableViewCell"
    let RedeemableReservationView = "RedeemableReservationView"
    let Settings = "Settings"
    let AssetPorvider = "ApplicationAssetPorvider"
    let CanceledReservationViewCell = "CanceledReservationViewCell"
    let RatingView = "RatingView"
    let MultipleOutletsOutletView = "MultipleOutletsOutletView"
    let MultipleOutletsOfferView = "MultipleOutletsOfferView"
    let MultipleOutletsOutletTableViewCell = "MultipleOutletsOutletTableViewCell"
    let MultipleOutletsOfferTableViewCell = "MultipleOutletsOfferTableViewCell"
    let ViewAllMultipleOutletsTableViewCell = "ViewAllMultipleOutletsTableViewCell"
    let HowToRedeemViewController = "HowToRedeemViewController"

    //Payment Method
    let AddPaymentMethodTableViewCell = "AddPaymentMethodTableViewCell"
    let AddPaymentMethodViewController = "AddPaymentMethodViewController"

    let RedeemMutipleOutletTableViewCell = "RedeemMutipleOutletTableViewCell"
    let RedeemMultipleOutletView = "RedeemMultipleOutletView"
    let EmptyNearbyViewController = "EmptyNearbyViewController"
    let ListingGroup = "ListingGroup"
    let ListingsGroupedOutletTableViewCell = "ListingsGroupedOutletTableViewCell"
    let ListingsGroupedOfferTableViewCell = "ListingsGroupedOfferTableViewCell"
    let ListingsHeaderSectionIdentifier = "ListingsHeaderSectionIdentifier"
    let ListingsFilterSectionIdentifier = "ListingsFilterSectionIdentifier"
    let ListingsListingsSectionIdentifier = "ListingsListingsSectionIdentifier"
    let ListingsViewAllOffersTableViewCell = "ListingsViewAllOffersTableViewCell"
    let ListingsGroupedAllOffers = "ListingsGroupedAllOffers"
    let ListingsGroupedAllOffersViewController = "ListingsGroupedAllOffersViewController"
    let ListingCollectionDetailTableViewCell = "ListingCollectionDetailTableViewCell"
}
